#pragma once

#define BOARD_PIN_LCD_RST GPIO_NUM_10
#define BOARD_PIN_LCD_BL GPIO_NUM_7
#define BOARD_PIN_LCD_CS GPIO_NUM_5
#define BOARD_PIN_LCD_DC GPIO_NUM_3
#define BOARD_PIN_LCD_MOSI GPIO_NUM_9
#define BOARD_PIN_LCD_SCLK GPIO_NUM_12
#define BOARD_PIN_LCD_MISO -1

#define BOARD_PIN_TOUCH_I2C_SCL GPIO_NUM_40
#define BOARD_PIN_TOUCH_I2C_SDA GPIO_NUM_41
#define BOARD_PIN_TOUCH_GPIO_INT GPIO_NUM_1
#define BOARD_PIN_TOUCH_RST GPIO_NUM_2

#define BOARD_PIN_THERMAL_UART_TX GPIO_NUM_4
#define BOARD_PIN_THERMAL_UART_RX GPIO_NUM_6

